server:
  port: 12001
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


app:
  thread-pool:
    core: 4
    max: 8
    keep-alive-time: 300
    queue-size: 2000