server:
  port: 7002
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web


app:
  thread-pool:
    core: 4
    max: 8
    keep-alive-time: 300
    queue-size: 2000









